apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-client
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-full-access
  namespace: agentic-ai
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-full-access
  namespace: agentic-ai
subjects:
  - kind: ServiceAccount
    name: argo-client
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-full-access
---
# Optional: allow ClusterWorkflowTemplates access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-full-access-cluster
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["clusterworkflowtemplates"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-full-access-cluster
subjects:
  - kind: ServiceAccount
    name: argo-client
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-full-access-cluster
---
# Token secret for the SA (K8s 1.24+)
apiVersion: v1
kind: Secret
metadata:
  name: argo-client.service-account-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: argo-client
type: kubernetes.io/service-account-token