apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-executor
  namespace: agentic-ai
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-executor
  namespace: agentic-ai
rules:
  # Core resources
  - apiGroups: [""]
    resources: [pods, pods/log, pods/exec, services, endpoints, configmaps, secrets, events, serviceaccounts]
    verbs: [get, list, watch, create, update, patch, delete]
  # Apps resources (Deployments, etc.)
  - apiGroups: ["apps"]
    resources: [deployments, daemonsets, statefulsets, replicasets]
    verbs: [get, list, watch, create, update, patch, delete]
  # Batch resources (if any Jobs/CronJobs appear in manifests)
  - apiGroups: ["batch"]
    resources: [jobs, cronjobs]
    verbs: [get, list, watch, create, update, patch, delete]
  # Argo often uses finalizers/owner refs; allow patch on workflow-owned objects
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-executor
  namespace: agentic-ai
subjects:
  - kind: ServiceAccount
    name: argo-executor
    namespace: agentic-ai
roleRef:
  kind: Role
  name: argo-executor
  apiGroup: rbac.authorization.k8s.io